id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2026-08-17T20:45:58.461Z
blockData:
  top: 48
  left: 48
  uuid: f719ff02-e2fb-484a-9fea-af85b34c6288
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
