private: false
customLibraries:
  array: []
name: childwfspot
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: ''
hasProtectedTriggers: false
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: 1202160b-be9d-4307-8d1d-7805c7db56c6
description: ''
sfSymbols:
  - childwfspot
  - workflowDiyaaYaqub2026081715256Pm
workflowTemplate:
  version: 4.43.0
