id: params
type: datasource
subtype: JavascriptQuery
resourceName: JavascriptQuery
template:
  ordered:
    - query: return null
    - evalType: script
createdAt: 2026-08-18T19:55:38.874Z
blockData:
  top: 48
  left: 48
  uuid: d809ec2d-394c-4a48-bff7-2cab489fbc5c
  options: {}
  pluginId: params
  blockType: webhook
  editorType: JavascriptQuery
  isMinimized: false
  resourceName: webhook
  incomingOnSuccessEdges: []
