private: false
customLibraries:
  array: []
name: query library wf
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: ''
hasProtectedTriggers: true
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: 663bdf61-4fc8-49b6-99ae-d75b98bf47e3
description: ''
sfSymbols:
  - queryLibraryWf
  - workflowDiyaaYaqub2026091540752Pm
workflowTemplate:
  version: 4.59.0
