private: false
customLibraries:
  array: []
name: parentwfspot
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: ''
hasProtectedTriggers: true
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: 60a7e550-559e-423e-8711-fc40156dc2c0
description: ''
sfSymbols:
  - parentwfspot
  - workflowDiyaaYaqub2026081715229Pm
workflowTemplate:
  version: 4.43.0
