private: false
customLibraries:
  array: []
name: childwf2
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: ''
hasProtectedTriggers: true
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: e3dad51e-c8bf-4aad-9dbf-55a39d827e50
description: ''
sfSymbols:
  - childwf2
  - workflowDiyaaYaqub2026081835515Pm
workflowTemplate:
  version: 4.44.0
