private: false
customLibraries:
  array: []
name: childwf3 (no loop)
setupScripts:
  object:
    python:
      object:
        codeString: ''
    javascript:
      object:
        codeString: ''
hasProtectedTriggers: false
triggerWebhooks:
  array:
    - object:
        name: startTrigger
        uuid: startTrigger
        headers: '{}'
        inputSchema:
          object:
            properties:
              array: []
        useHeaderApiKey: false
        exampleInputJSON: ''
        examplePathParams: ''
version: 43.0.9
workflowId: 69d07395-3d05-4bb7-8bc0-e5da2c177acb
description: ''
sfSymbols:
  - childwf3NoLoop
  - workflowDiyaaYaqub2026081843714Pm
workflowTemplate:
  version: 4.44.0
